"use client";
import "./globals.css";
import LinkButton from "./components/LinkButton";
import { usePathname } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body>
        <nav className="w-full h-[48px]">
          <LinkButton text={pathname === "/" ? "LOGIN" : "BACK"} />
        </nav>
        {children}
      </body>
    </html>
  );
}
