import "./globals.css";
import LinkButton from "./components/LinkButton";
import FormDataProvider from '././components/contexts/FormDataContext'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav className="w-full h-[48px]">
          <LinkButton text="BACK" />
        </nav>
        <FormDataProvider>
          {children}
        </FormDataProvider>
      </body>
    </html>
  );
}
